In [ ]:
#Description: Scrape the top 10 cryptocurrencies by market cap

In [27]:
#import librabries
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [28]:
#create empty lists to store data
name_list = []
market_cap_list = []
price_list = []
circulating_supply_list = []
symbol_list = []

In [29]:
#create dataframe 
df = pd.DataFrame()

In [30]:
#create a function to scrape data based on datetime
#https://coinmarketcap.com/historical/20240623/
def scrape(date = '20240623/'):
    #get the URL of the website + date that we want to scrape
    URL = 'https://coinmarketcap.com/historical/'+ date
    
    #make a request to the website
    webpage = requests.get(URL)
    
    #parse the text from website
    soup = BeautifulSoup(webpage.text, 'html.parser')
    
    #get the table row element
    tr = soup.find_all('tr', attrs= {'class': 'cmc-table-row'})
    
    #create a count variable for the number of crypto currencies that we want to scrape
    count = 0
    
    #loop through every row to gather the data
    for row in tr:
        #if the count is reached then break out of the loop
        if count == 10:
            break;
        count = count + 1 #increament count by 1
        
        #store the name of the cryptocurrency into variable
        #find the <td> element to later get the cryptocurrency name
        name_column = row.find('td', attrs = {'class': 'cmc-table__cell cmc-table__cell--sticky cmc-table__cell--sortable cmc-table__cell--left cmc-table__cell--sort-by__name'})
        name = name_column.find('a', attrs = {'class': 'cmc-table__column-name--name cmc-link'}).text.strip()    
        #store the coin market cap of the cryptocurrency/coin into variable
        market_cap = row.find('td', attrs = {'class':"cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__market-cap"}).text.strip()        
        #find and store crypto price
        price = row.find('td', attrs = {'class': 'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__price'}).text.strip()        
        #find and store crypto circulating_supply
        circulating_supply_symbol = row.find('td', attrs = {'class': 'cmc-table__cell cmc-table__cell--sortable cmc-table__cell--right cmc-table__cell--sort-by__circulating-supply'}).text.strip()        
        #split the data
        circulating_supply = circulating_supply_symbol.split(' ')[0]
        symbol = circulating_supply_symbol.split(' ')[1]
        
        #append the data to the lists
        name_list.append(name)
        market_cap_list.append(market_cap)
        price_list.append(price)
        circulating_supply_list.append(circulating_supply)
        symbol_list.append(symbol)

In [31]:
#run the scrape function
scrape(date = '20240623/')

In [33]:
#store the data into a dataframe to organize data
df['Name'] = name_list
df['Market Cap'] = market_cap_list
df['Price'] = price_list
df['Circulating Supply'] = circulating_supply_list
df['Symbol'] = symbol_list

#show data
df.head(10)

          Name             Market Cap       Price Circulating Supply Symbol
0      Bitcoin  $1,245,656,822,237.84  $63,180.80         19,715,750    BTC
1     Ethereum    $418,014,043,658.50   $3,418.61        122,275,958    ETH
2  Tether USDt    $112,867,606,177.86     $0.9993    112,941,691,563   USDT
3          BNB     $85,176,655,492.80     $577.21        147,565,918    BNB
4       Solana     $59,426,969,914.39     $128.59        462,141,478    SOL
5         USDC     $32,708,794,131.71     $0.9999     32,710,488,116   USDC
6          XRP     $26,668,285,443.74     $0.4795     55,618,185,850    XRP
7      Toncoin     $18,468,364,592.55     $7.5128      2,458,268,089    TON
8     Dogecoin     $17,706,912,005.85     $0.1223    144,834,016,384   DOGE
9      Cardano     $13,593,261,157.59     $0.3803     35,743,210,893    ADA